FROM docker.io/library/postgres:18

RUN apt-get update && apt-get install -y pgbackrest \
    && rm -rf /var/lib/apt/lists/*

COPY init.sh /docker-entrypoint-initdb.d/01-aifs.sh
RUN chmod +x /docker-entrypoint-initdb.d/01-aifs.sh
