/**
 * Wails Go bindings — auto-generated by `wails generate` in a real build.
 * This file is hand-maintained to match gui/app.go.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const call = (method: string, ...args: unknown[]) => (window as any).go.main.App[method](...args)

export interface InstanceInfo {
  name: string
  status: string
  running: boolean
  pgUrl: string
  mountPath: string
  isFormatted: boolean
}

export interface BenchResult {
  writeBigMiBs: number
  writeBigSecsPerFile: number
  readBigMiBs: number
  readBigSecsPerFile: number
  writeSmallPerSec: number
  writeSmallMsPerFile: number
  readSmallPerSec: number
  readSmallMsPerFile: number
  statPerSec: number
  statMsPerFile: number
}

export interface Snapshot {
  name: string
  type: string
  timestamp: string  // ISO 8601 backup start time
  stop_time: string  // ISO 8601 earliest restore point
  size: number       // bytes
}

export interface CreateInstanceRequest {
  name: string
  data_dir: string
  pitr_enabled: boolean
}

export const CreateInstance = (req: CreateInstanceRequest): Promise<void> => call('CreateInstance', req)

export interface ConfigStatus {
  exists: boolean
  path: string
  baseDir: string
}

export const GetConfigStatus = (): Promise<ConfigStatus> => call('GetConfigStatus')
export const InitConfig = (baseDir: string): Promise<void> => call('InitConfig', baseDir)

export const FormatInstance = (name: string): Promise<void> => call('FormatInstance', name)
export const ListInstances = (): Promise<InstanceInfo[]> => call('ListInstances')
export const StartInstance = (name: string): Promise<void> => call('StartInstance', name)
export const StopInstance = (name: string): Promise<void> => call('StopInstance', name)
export const MountInstance = (name: string, mountpoint: string): Promise<void> => call('MountInstance', name, mountpoint)
export const UmountInstance = (mountpoint: string): Promise<void> => call('UmountInstance', mountpoint)

export const ListSnapshots = (name: string): Promise<Snapshot[]> => call('ListSnapshots', name)
export const CreateSnapshot = (name: string, snapType: string): Promise<void> => call('CreateSnapshot', name, snapType)
export const DeleteSnapshot = (name: string, snapName: string): Promise<void> => call('DeleteSnapshot', name, snapName)
export const RestoreInstance = (name: string, targetTime: string, promote: boolean): Promise<void> =>
  call('RestoreInstance', name, targetTime, promote)

export const RunBench = (path: string, bigSize: string, threads: number): Promise<BenchResult> =>
  call('RunBench', path, bigSize, threads)

export const GetConfigPath = (): Promise<string> => call('GetConfigPath')
export const OpenConfigFile = (): Promise<void> => call('OpenConfigFile')
export const ShowConfirm = (title: string, message: string): Promise<boolean> => call('ShowConfirm', title, message)
export const ShowAlert = (title: string, message: string): Promise<void> => call('ShowAlert', title, message)
