// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {pitr} from '../models';

export function CreateInstance(arg1:main.CreateInstanceRequest):Promise<void>;

export function CreateSnapshot(arg1:string,arg2:string):Promise<void>;

export function DeleteSnapshot(arg1:string,arg2:string):Promise<void>;

export function FormatInstance(arg1:string):Promise<void>;

export function GetConfigPath():Promise<string>;

export function GetConfigStatus():Promise<main.ConfigStatus>;

export function InitConfig(arg1:string):Promise<void>;

export function ListInstances():Promise<Array<main.InstanceInfo>>;

export function ListSnapshots(arg1:string):Promise<Array<pitr.Snapshot>>;

export function MountInstance(arg1:string,arg2:string):Promise<void>;

export function OpenConfigFile():Promise<void>;

export function RestoreInstance(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function RunBench(arg1:string,arg2:string,arg3:number):Promise<main.BenchResult>;

export function StartInstance(arg1:string):Promise<void>;

export function StopInstance(arg1:string):Promise<void>;

export function UmountInstance(arg1:string):Promise<void>;
