// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSnapshot(arg1, arg2) {
  return window['go']['main']['App']['CreateSnapshot'](arg1, arg2);
}

export function DeleteSnapshot(arg1, arg2) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1, arg2);
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function ListInstances() {
  return window['go']['main']['App']['ListInstances']();
}

export function ListSnapshots(arg1) {
  return window['go']['main']['App']['ListSnapshots'](arg1);
}

export function MountInstance(arg1, arg2) {
  return window['go']['main']['App']['MountInstance'](arg1, arg2);
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function RestoreInstance(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreInstance'](arg1, arg2, arg3);
}

export function RunBench(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunBench'](arg1, arg2, arg3);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StopInstance(arg1) {
  return window['go']['main']['App']['StopInstance'](arg1);
}

export function UmountInstance(arg1) {
  return window['go']['main']['App']['UmountInstance'](arg1);
}
